// frontend/src/components/CommandSheet.svelte
<script lang="ts">
  import BottomSheet from './BottomSheet.svelte';
  import { desktop } from '../lib/desktop.svelte';
  import * as m from '../paraglide/messages';
  import type { CommandInfo } from '@hangar/core';
  import { skipChatConfirmations, rememberSkipChatConfirmations } from '../lib/confirmActions';

  // Folha de comandos: busca no topo + lista agrupada (Built-ins, Suas skills, Plugins).
  // Comportamento ao tocar: destrutivos pedem confirmacao inline; model/effort abrem o
  // popover de modelo do Claude (evita o TUI cego do /model); comandos com argumento preenchem o
  // textarea; o resto envia direto.
  interface Props {
    open: boolean;
    commands: CommandInfo[];
    fillOnly?: boolean;
    onCommand: (cmd: string) => void; // envia "/nome"
    onFill: (name: string) => void; // preenche "/nome " no textarea
    /** Qual das duas caixas abrir: `/model` e `/effort` viraram pills separadas. */
    onOpenModelEffort: (qual: 'model' | 'effort') => void;
    onClose: () => void;
  }
  let { open, commands, fillOnly = false, onCommand, onFill, onOpenModelEffort, onClose }: Props = $props();

  let query = $state('');
  let confirming = $state<string | null>(null);
  let skipNext = $state(false);
  let saveError = $state(false);

  // Zera busca e confirmacao toda vez que a folha abre.
  $effect(() => {
    if (open) {
      query = '';
      confirming = null;
      skipNext = false;
      saveError = false;
    }
  });

  function matches(c: CommandInfo): boolean {
    const q = query.trim().toLowerCase();
    if (!q) return true;
    return (
      c.name.toLowerCase().includes(q) ||
      (descricao(c)?.toLowerCase().includes(q) ?? false)
    );
  }

  const filtered = $derived(commands.filter(matches));
  const groups = $derived(
    (
      [
        { key: 'builtin', label: m.comandos_builtins() },
        { key: 'skill', label: m.comandos_suas_skills() },
        { key: 'plugin', label: m.comandos_plugins() },
      ] as const
    )
      .map((g) => ({ ...g, items: filtered.filter((c) => c.source === g.key) }))
      .filter((g) => g.items.length > 0)
  );

  function handleTap(c: CommandInfo) {
    if (fillOnly) {
      onFill(c.name);
      onClose();
      return;
    }
    if (c.name === 'model' || c.name === 'effort') {
      onOpenModelEffort(c.name === 'effort' ? 'effort' : 'model');
      onClose();
      return;
    }
    if (c.destructive) {
      if (skipChatConfirmations()) { onCommand('/' + c.name); onClose(); return; }
      confirming = c.name; // pede confirmacao inline antes de enviar
      skipNext = false;
      saveError = false;
      return;
    }
    if (c.argumentHint) {
      onFill(c.name); // tem argumento -> preenche e deixa o usuario digitar
      onClose();
      return;
    }
    onCommand('/' + c.name); // zero-arg -> envia
    onClose();
  }

  function confirm(c: CommandInfo) {
    if (skipNext && !rememberSkipChatConfirmations()) { saveError = true; return; }
    confirming = null;
    onCommand('/' + c.name);
    onClose();
  }

  function badge(source: CommandInfo['source']): string {
    return source === 'builtin' ? 'base' : source === 'plugin' ? 'plugin' : 'skill';
  }

  // Descrições dos built-ins são INTERFACE (o catálogo fixo do Claude Code), então vivem em
  // chaves traduzidas aqui no front — o backend manda o nome + a description em pt como fallback
  // (skills/plugins seguem cruas de propósito: frontmatter do usuário é dado, não interface).
  const DESCRICAO_BUILTIN: Record<string, () => string> = {
    clear: m.cmd_clear,
    compact: m.cmd_compact,
    context: m.cmd_context,
    model: m.cmd_model,
    effort: m.cmd_effort,
    resume: m.cmd_resume,
    rewind: m.cmd_rewind,
    'release-notes': m.cmd_release_notes,
    help: m.cmd_help,
    status: m.cmd_status,
    cost: m.cmd_cost,
    export: m.cmd_export,
    init: m.cmd_init,
    agents: m.cmd_agents,
    mcp: m.cmd_mcp,
    memory: m.cmd_memory,
    vim: m.cmd_vim,
    config: m.cmd_config,
    doctor: m.cmd_doctor,
    quit: m.cmd_quit,
  };

  function descricao(c: CommandInfo): string | null {
    if (c.source === 'builtin') {
      const t = DESCRICAO_BUILTIN[c.name];
      if (t) return t();
    }
    return c.description ?? null;
  }
</script>

<BottomSheet {open} {onClose} ariaLabel={m.comandos_titulo()} wide={desktop.atual} centered={desktop.atual}>
  <h2 class="sheet-title">{m.comandos_titulo()}</h2>

  <input
    type="text"
    class="search"
    bind:value={query}
    placeholder={m.comandos_buscar()}
    autocomplete="off"
    autocorrect="off"
    autocapitalize="off"
    spellcheck={false}
    aria-label={m.comandos_buscar()}
  />

  {#if groups.length === 0}
    <p class="empty">{m.comandos_vazio()}</p>
  {:else}
    <div class="groups">
      {#each groups as g (g.key)}
        <section class="group">
          <h3 class="group-label">{g.label}</h3>
          <ul class="cmd-list">
            {#each g.items as c (c.source + ':' + c.name)}
              <li>
                {#if confirming === c.name}
                  <div class="cmd-row cmd-row--confirm">
                    <span class="confirm-text">{m.comandos_confirmar({ n: c.display })}</span>
                    <div class="confirm-actions">
                      <button class="cbtn cbtn--no" onclick={() => (confirming = null)}>{m.comandos_nao()}</button>
                      <button class="cbtn cbtn--yes" onclick={() => confirm(c)}>{m.comandos_sim()}</button>
                    </div>
                    <label class="confirm-skip"><input type="checkbox" bind:checked={skipNext} onchange={() => (saveError = false)} />{m.confirm_no_ask_actions()}</label>
                    {#if saveError}<span class="confirm-error" role="alert">{m.confirm_no_ask_save_failed()}</span>{/if}
                  </div>
                {:else}
                  <button class="cmd-row" onclick={() => handleTap(c)}>
                    <span class="cmd-main">
                      <span class="cmd-name">{c.display}</span>
                      {#if descricao(c)}<span class="cmd-desc">{descricao(c)}</span>{/if}
                    </span>
                    {#if c.argumentHint}<span class="arg">{c.argumentHint}</span>{/if}
                    <span class="badge badge--{c.source}">{badge(c.source)}</span>
                  </button>
                {/if}
              </li>
            {/each}
          </ul>
        </section>
      {/each}
    </div>
  {/if}
</BottomSheet>

<style>
  .sheet-title {
    font-size: var(--text-xl);
    font-weight: 600;
    color: var(--text-primary);
    margin-bottom: var(--space-4);
  }

  .search {
    width: 100%;
    height: 44px;
    background: var(--bg-surface);
    border: 1px solid var(--border-default);
    border-radius: var(--radius-md);
    color: var(--text-primary);
    font-family: var(--font-ui);
    font-size: 16px; /* evita zoom no iOS */
    padding: 0 var(--space-3);
    outline: none;
    margin-bottom: var(--space-4);
    transition: border-color 180ms var(--ease-out);
  }

  .search::placeholder {
    color: var(--text-muted);
  }

  .search:focus {
    border-color: var(--accent);
    box-shadow: 0 0 0 2px var(--accent-dim);
  }

  .groups {
    display: flex;
    flex-direction: column;
    gap: var(--space-4);
    max-height: 52vh;
    overflow-y: auto;
  }

  .group-label {
    font-size: var(--text-sm);
    font-weight: 600;
    color: var(--text-secondary);
    margin-bottom: var(--space-2);
  }

  .cmd-list {
    list-style: none;
    display: flex;
    flex-direction: column;
    gap: var(--space-1);
  }

  .cmd-row {
    width: 100%;
    min-height: 44px;
    display: flex;
    align-items: center;
    gap: var(--space-2);
    padding: var(--space-2) var(--space-3);
    border-radius: var(--radius-md);
    text-align: left;
    background: transparent;
    transition: background 160ms var(--ease-out);
  }

  .cmd-row:active {
    background: var(--bg-hover);
  }

  .cmd-main {
    display: flex;
    flex-direction: column;
    gap: 2px;
    min-width: 0;
    flex: 1;
  }

  .cmd-name {
    font-family: var(--font-mono);
    font-size: var(--text-base);
    font-weight: 600;
    color: var(--text-primary);
  }

  .cmd-desc {
    font-size: var(--text-sm);
    color: var(--text-muted);
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
  }

  .arg {
    font-family: var(--font-mono);
    font-size: var(--text-xs);
    color: var(--text-secondary);
    white-space: nowrap;
    flex-shrink: 0;
  }

  .badge {
    flex-shrink: 0;
    font-size: 10px;
    font-weight: 600;
    text-transform: uppercase;
    letter-spacing: 0.04em;
    padding: 2px 6px;
    border-radius: var(--radius-full);
    color: var(--text-secondary);
    background: var(--bg-hover);
  }

  .badge--skill {
    color: var(--accent);
    background: var(--accent-dim);
  }

  .badge--plugin {
    color: var(--warning);
    background: rgba(255, 159, 10, 0.14);
  }

  /* ── Confirmacao inline de comando destrutivo ───────────────────────────── */
  .cmd-row--confirm {
    display: flex;
    align-items: center;
    justify-content: space-between;
    flex-wrap: wrap;
    gap: var(--space-2);
    min-height: 44px;
    padding: var(--space-2) var(--space-3);
    border-radius: var(--radius-md);
    background: var(--pill-dead-bg);
  }

  .confirm-text {
    font-size: var(--text-sm);
    color: var(--text-primary);
    min-width: 0;
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
  }

  .confirm-actions {
    display: flex;
    gap: var(--space-2);
    flex-shrink: 0;
  }

  .confirm-skip { width: 100%; display: flex; align-items: center; gap: var(--space-2); font-size: var(--text-sm); color: var(--text-secondary); }
  .confirm-skip input { width: 20px; height: 20px; accent-color: var(--accent); }
  .confirm-error { width: 100%; font-size: var(--text-sm); color: var(--error); }

  .cbtn {
    padding: 0 var(--space-3);
    border-radius: var(--radius-sm);
    font-size: var(--text-sm);
    font-weight: 600;
  }

  .cbtn--no {
    color: var(--text-secondary);
    background: var(--bg-hover);
  }

  .cbtn--yes {
    color: #fff;
    background: var(--error);
  }

  .empty {
    font-size: var(--text-sm);
    color: var(--text-muted);
    text-align: center;
    padding: var(--space-4) 0;
  }
</style>

// mobile/src/chat/CommandSheet.tsx
import { useCallback, useEffect, useRef, useState } from 'react';
import { ActivityIndicator, Alert, Pressable, ScrollView, Text, TextInput, View } from 'react-native';
import { StyleSheet, useUnistyles } from 'react-native-unistyles';
import { getCommands } from '@hangar/core';
import type { CommandInfo } from '@hangar/core';
import { Sheet } from '../ui/Sheet';
import { superficie } from '../theme/superficie';
import * as m from '../paraglide/messages';

// Uma busca por sessão: a lista vale para a folha e para as sugestões em linha, e não muda entre
// aberturas. No Codex ela não fica guardada, como no PWA.
const cache = new Map<string, CommandInfo[]>();

export function useSessionCommands(name: string, provider: string | null, wanted: boolean) {
  const key = `${provider ?? 'claude'}|${name}`;
  const [commands, setCommands] = useState<CommandInfo[] | null>(() => cache.get(key) ?? null);
  const [error, setError] = useState('');
  const [attempt, setAttempt] = useState(0);

  useEffect(() => {
    if (!wanted || commands) return;
    let alive = true;
    setError('');
    getCommands(name)
      .then((c) => {
        if (provider !== 'codex') cache.set(key, c);
        if (alive) setCommands(c);
      })
      .catch((e: unknown) => {
        if (alive) setError(e instanceof Error ? e.message : String(e));
      });
    return () => { alive = false; };
  }, [wanted, commands, name, provider, key, attempt]);

  const retry = useCallback(() => setAttempt((n) => n + 1), []);
  return { commands, error, retry };
}

// Descrições dos built-ins são interface (o catálogo fixo do Claude Code), então são traduzidas
// aqui; as de skills e plugins vêm do frontmatter do usuário e passam cruas.
const BUILTIN_DESCRIPTION: Record<string, () => string> = {
  clear: m.cmd_clear,
  compact: m.cmd_compact,
  context: m.cmd_context,
  model: m.cmd_model,
  effort: m.cmd_effort,
  resume: m.cmd_resume,
  rewind: m.cmd_rewind,
  'release-notes': m.cmd_release_notes,
  help: m.cmd_help,
  status: m.cmd_status,
  cost: m.cmd_cost,
  export: m.cmd_export,
  init: m.cmd_init,
  agents: m.cmd_agents,
  mcp: m.cmd_mcp,
  memory: m.cmd_memory,
  vim: m.cmd_vim,
  config: m.cmd_config,
  doctor: m.cmd_doctor,
  quit: m.cmd_quit,
};

export function commandDescription(c: CommandInfo): string | null {
  return (c.source === 'builtin' ? BUILTIN_DESCRIPTION[c.name]?.() : undefined) ?? c.description ?? null;
}

export function confirmDestructive(c: CommandInfo, run: () => void) {
  Alert.alert(m.comandos_confirmar({ n: c.display }), commandDescription(c) ?? undefined, [
    { text: m.comandos_nao(), style: 'cancel' },
    { text: m.comandos_sim(), style: 'destructive', onPress: run },
  ]);
}

const sourceBadge = (source: CommandInfo['source']) => (source === 'builtin' ? 'base' : source);

// Folha de comandos: busca, grupos e a ação de cada um — `/model` e `/effort` abrem o seletor,
// destrutivo pergunta antes, com argumento preenche o campo, o resto envia na hora.
export function CommandSheet({
  open,
  onClose,
  commands,
  error,
  onRetry,
  fillOnly,
  onCommand,
  onFill,
  onOpenModelEffort,
}: {
  open: boolean;
  onClose: () => void;
  commands: CommandInfo[] | null;
  error: string;
  onRetry: () => void;
  // Codex: tocar só preenche, a pessoa revisa e envia.
  fillOnly: boolean;
  onCommand: (cmd: string) => void;
  onFill: (name: string) => void;
  onOpenModelEffort: (which: 'model' | 'effort') => void;
}) {
  const { theme } = useUnistyles();
  const [query, setQuery] = useState('');

  useEffect(() => {
    if (open) setQuery('');
  }, [open]);

  const q = query.trim().toLowerCase();
  const filtered = (commands ?? []).filter((c) => !q || c.name.toLowerCase().includes(q)
    || (commandDescription(c)?.toLowerCase().includes(q) ?? false));
  const groups = ([
    { key: 'builtin', label: m.comandos_builtins() },
    { key: 'skill', label: m.comandos_suas_skills() },
    { key: 'plugin', label: m.comandos_plugins() },
  ] as const)
    .map((g) => ({ ...g, items: filtered.filter((c) => c.source === g.key) }))
    .filter((g) => g.items.length > 0);

  // A ação roda depois que a folha some: outra folha (seletor, pergunta lateral) apresentada no
  // meio do fechamento desta não abre.
  const afterClose = useRef<(() => void) | null>(null);
  const finish = (action: () => void) => {
    afterClose.current = action;
    onClose();
  };
  const tap = (c: CommandInfo) => {
    if (fillOnly) { finish(() => onFill(c.name)); return; }
    if (c.name === 'model' || c.name === 'effort') { finish(() => onOpenModelEffort(c.name as 'model' | 'effort')); return; }
    if (c.destructive) { confirmDestructive(c, () => finish(() => onCommand('/' + c.name))); return; }
    if (c.argumentHint) { finish(() => onFill(c.name)); return; }
    finish(() => onCommand('/' + c.name));
  };

  return (
    <Sheet
      open={open}
      sizes={['large']}
      onDismiss={() => {
        onClose();
        const action = afterClose.current;
        afterClose.current = null;
        action?.();
      }}
      scrollable
    >
      <ScrollView contentContainerStyle={styles.inner} keyboardShouldPersistTaps="handled">
        <Text style={[styles.title, { color: theme.tokens.text.primary }]} accessibilityRole="header">{m.comandos_titulo()}</Text>
        <TextInput
          value={query}
          onChangeText={setQuery}
          placeholder={m.comandos_buscar()}
          placeholderTextColor={theme.tokens.text.muted}
          accessibilityLabel={m.comandos_buscar()}
          autoCapitalize="none"
          autoCorrect={false}
          style={[styles.search, { color: theme.tokens.text.primary, backgroundColor: superficie(theme, 0.6), borderColor: theme.tokens.border.subtle }]}
        />
        {error ? (
          <View style={styles.centro}>
            <Text style={[styles.muted, { color: theme.tokens.status.error }]}>{error}</Text>
            <Pressable onPress={onRetry} accessibilityRole="button" style={styles.retry}>
              <Text style={[styles.retryTxt, { color: theme.tokens.accent.base }]}>{m.lista_tentar_novamente()}</Text>
            </Pressable>
          </View>
        ) : !commands ? (
          <ActivityIndicator color={theme.tokens.text.secondary} />
        ) : groups.length === 0 ? (
          <Text style={[styles.muted, { color: theme.tokens.text.muted }]}>{m.comandos_vazio()}</Text>
        ) : (
          groups.map((g) => (
            <View key={g.key} style={styles.group}>
              <Text style={[styles.groupLabel, { color: theme.tokens.text.muted }]} accessibilityRole="header">{g.label}</Text>
              {g.items.map((c) => {
                const desc = commandDescription(c);
                return (
                  <Pressable
                    key={`${c.source}:${c.name}`}
                    onPress={() => tap(c)}
                    style={({ pressed }) => [styles.item, pressed && { backgroundColor: theme.tokens.bg.hover }]}
                    accessibilityRole="button"
                    accessibilityLabel={c.display}
                    accessibilityHint={desc ?? undefined}
                  >
                    <View style={styles.txt}>
                      <Text style={[styles.nome, { color: theme.tokens.text.primary }]} numberOfLines={1}>
                        {c.display}
                        {c.argumentHint ? <Text style={{ color: theme.tokens.text.muted }}> {c.argumentHint}</Text> : null}
                      </Text>
                      {desc ? (
                        <Text style={[styles.desc, { color: theme.tokens.text.muted }]} numberOfLines={2}>{desc}</Text>
                      ) : null}
                    </View>
                    <Text style={[styles.badge, { color: theme.tokens.text.muted, borderColor: theme.tokens.border.subtle }]}>{sourceBadge(c.source)}</Text>
                  </Pressable>
                );
              })}
            </View>
          ))
        )}
      </ScrollView>
    </Sheet>
  );
}

const styles = StyleSheet.create((theme) => ({
  inner: { gap: theme.base.space[1], padding: theme.base.space[3] },
  title: { fontSize: theme.base.text.base, fontWeight: '600', marginBottom: theme.base.space[1] },
  search: {
    minHeight: 44,
    borderWidth: 1,
    borderRadius: theme.base.radius.md,
    paddingHorizontal: theme.base.space[3],
    fontSize: theme.base.text.base,
    marginBottom: theme.base.space[2],
  },
  muted: { fontSize: theme.base.text.sm, textAlign: 'center', paddingVertical: theme.base.space[3] },
  centro: { alignItems: 'center', gap: theme.base.space[1] },
  retry: { minHeight: 44, justifyContent: 'center' },
  retryTxt: { fontSize: theme.base.text.sm, fontWeight: '600' },
  group: { gap: 2, marginBottom: theme.base.space[2] },
  groupLabel: { fontSize: theme.base.text.xs, fontWeight: '600', textTransform: 'uppercase', paddingHorizontal: theme.base.space[2] },
  item: {
    minHeight: 48,
    flexDirection: 'row',
    alignItems: 'center',
    gap: theme.base.space[2],
    paddingHorizontal: theme.base.space[2],
    paddingVertical: theme.base.space[1],
    borderRadius: theme.base.radius.md,
  },
  txt: { flex: 1, gap: 1 },
  nome: { fontSize: theme.base.text.base, fontFamily: theme.base.fontMono },
  desc: { fontSize: theme.base.text.xs },
  badge: {
    fontSize: theme.base.text.xxs,
    borderWidth: 1,
    borderRadius: theme.base.radius.full,
    paddingHorizontal: 6,
    paddingVertical: 1,
    overflow: 'hidden',
  },
}));
