// mobile/src/features/create/CodexContextControl.tsx
import { useCallback, useEffect, useRef, useState } from 'react';
import { Pressable, Switch, Text, View } from 'react-native';
import { StyleSheet } from 'react-native-unistyles';
import { codexOpcoes, type Server } from '@hangar/core';
import * as m from '../../paraglide/messages';

export function CodexContextControl({ server, onBusy }: { server: Server | null; onBusy: (busy: boolean) => void }) {
  const [enabled, setEnabled] = useState(false);
  // Valor escolhido enquanto a gravacao nao volta: o switch mostra ele na hora. Preso ao valor
  // confirmado, o toque parecia nao ter pegado.
  const [pedido, setPedido] = useState<boolean | null>(null);
  const [ready, setReady] = useState(false);
  const [busy, setBusy] = useState(true);
  const [error, setError] = useState('');
  const controller = useRef<AbortController | null>(null);

  const update = useCallback(async (control: AbortController, value?: boolean) => {
    setBusy(true);
    onBusy(true);
    setError('');
    if (value !== undefined) setPedido(value);
    try {
      const result = await codexOpcoes(server, control.signal, value);
      if (controller.current !== control || control.signal.aborted) return;
      setEnabled(result.contexto_estendido);
      setReady(true);
    } catch (e) {
      if (controller.current === control && !control.signal.aborted) {
        setError(e instanceof Error ? e.message : m.comum_falha_aplicar());
      }
    } finally {
      if (controller.current === control && !control.signal.aborted) {
        setBusy(false);
        setPedido(null);
        onBusy(false);
      }
    }
  }, [server, onBusy]);

  useEffect(() => {
    const control = new AbortController();
    controller.current = control;
    setReady(false);
    void update(control);
    return () => { control.abort(); onBusy(false); };
  }, [update, onBusy]);

  return (
    <View style={styles.root}>
      <View style={styles.row}>
        <Text style={styles.label}>{m.codex_contexto_titulo()}</Text>
        <Switch accessibilityLabel={m.codex_contexto_titulo()} value={pedido ?? enabled} disabled={busy || !ready}
          onValueChange={(value) => { if (controller.current) void update(controller.current, value); }} />
      </View>
      <Text style={styles.hint}>{m.codex_contexto_padrao()}</Text>
      {busy ? <Text style={styles.hint} accessibilityRole="text">
        {pedido !== null ? m.codex_contexto_salvando() : m.comum_carregando()}</Text> : null}
      {error ? <>
        <Text style={styles.error} accessibilityRole="alert">{error}</Text>
        <Pressable accessibilityRole="button" disabled={busy} style={styles.retry}
          onPress={() => { if (controller.current) void update(controller.current); }}>
          <Text style={styles.label}>{m.config_server_tentar_de_novo()}</Text>
        </Pressable>
      </> : null}
    </View>
  );
}

const styles = StyleSheet.create((theme) => ({
  root: { gap: theme.base.space[2] },
  row: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', minHeight: 44, gap: 12 },
  label: { color: theme.tokens.text.primary, flexShrink: 1 },
  hint: { color: theme.tokens.text.secondary, fontSize: 12 },
  error: { color: theme.tokens.status.error, fontSize: 12 },
  retry: { minHeight: 44, justifyContent: 'center' },
}));

// frontend/src/components/CodexContextControl.svelte
<script lang="ts">
  import { codexOpcoes, type Server } from '@hangar/core';
  import * as m from '../paraglide/messages';

  let { server, busy = $bindable(false) }: { server: Server | null; busy?: boolean } = $props();
  let enabled = $state(false);
  // O valor que a pessoa ESCOLHEU enquanto a gravação não volta: o switch mostra ele na hora.
  // Desfazer a marca e esperar o servidor fazia o clique parecer não ter pegado.
  let pedido = $state<boolean | null>(null);
  let ready = $state(false);
  let error = $state('');
  let context: { server: Server | null; controller: AbortController };

  async function update(ctx: typeof context, value?: boolean) {
    busy = true;
    error = '';
    if (value !== undefined) pedido = value;
    try {
      const result = await codexOpcoes(ctx.server, ctx.controller.signal, value);
      if (context !== ctx || ctx.controller.signal.aborted) return;
      enabled = result.contexto_estendido;
      ready = true;
    } catch (e) {
      if (context === ctx && !ctx.controller.signal.aborted) {
        error = e instanceof Error ? e.message : m.comum_falha_aplicar();
      }
    } finally {
      // Falhou ou confirmou: quem manda de novo é o valor do servidor.
      if (context === ctx && !ctx.controller.signal.aborted) { busy = false; pedido = null; }
    }
  }

  $effect(() => {
    const ctx = { server, controller: new AbortController() };
    context = ctx;
    ready = false;
    pedido = null;
    void update(ctx);
    return () => { ctx.controller.abort(); busy = false; };
  });
</script>

<div class="context-control">
  <label class:carregando={!ready}>
    <input type="checkbox" role="switch" checked={pedido ?? enabled} disabled={busy || !ready}
      onchange={(e) => { e.currentTarget.checked = !enabled; void update(context, !enabled); }} />
    <span class="titulo">{m.codex_contexto_titulo()}</span>
    {#if busy && pedido !== null}<span class="estado" role="status">{m.codex_contexto_salvando()}</span>
    {:else if busy}<span class="estado" role="status">{m.comum_carregando()}</span>{/if}
  </label>
  <p>{m.codex_contexto_padrao()}</p>
  {#if error}
    <p role="alert">{error}</p>
    <button type="button" disabled={busy} onclick={() => update(context)}>{m.config_server_tentar_de_novo()}</button>
  {/if}
</div>

<style>
  .context-control { display: grid; grid-column: 1 / -1; gap: var(--space-2); }
  /* A linha inteira é o alvo do toque, com o switch colado ao nome: a caixa de 20px no canto
     oposto da linha era difícil de acertar. */
  label { display: flex; align-items: center; gap: var(--space-3); min-height: 44px;
          padding: 0 var(--space-2); margin: 0 calc(-1 * var(--space-2));
          border-radius: var(--radius-md); font-size: var(--text-sm); cursor: pointer; }
  label:hover { background: var(--surface-raised); }
  label.carregando { cursor: progress; }
  input { flex: none; width: 22px; height: 22px; margin: 0; accent-color: var(--accent); cursor: inherit; }
  .titulo { flex: 1; }
  .estado { font-size: var(--text-xs); color: var(--text-secondary); }
  p { margin: 0; font-size: var(--text-xs); color: var(--text-secondary); }
  [role="alert"] { color: var(--error); }
  button { min-height: 44px; background: var(--surface-raised); border-radius: var(--radius-md); }
</style>
