// frontend/src/components/ConversationList.svelte
<script lang="ts">
  import { onMount, untrack } from 'svelte';
  import * as m from '../paraglide/messages';
  import ProviderGlyph from './icons/ProviderGlyph.svelte';
  import { getArchiveRecentForServer, relativeTime, type ArchiveEntry } from '@hangar/core';
  import { listOwnServers } from '../lib/auth';
  import { sessionsStore } from '../lib/sessionsStore.svelte';
  import { mergeConversations, rememberEntry } from '../lib/conversationList';

  interface Props {
    onNavigateToChat: (serverId: string, name: string) => void;
  }
  let { onNavigateToChat }: Props = $props();

  let closedByServer = $state(new Map<string, ArchiveEntry[]>());
  let failed = $state<string[]>([]);
  let loaded = $state(false);

  const ownIds = $derived(new Set(listOwnServers().map((s) => s.id)));
  const live = $derived(sessionsStore.rows.filter((s) => ownIds.has(s.serverId)));
  const rows = $derived(mergeConversations(live, closedByServer));

  let seq = 0;
  async function load() {
    const mine = ++seq;
    // Servidor em espera/offline não é consultado: cada tentativa custaria o teto de 8s da lista inteira.
    const down = new Set(sessionsStore.byServer.filter((b) => b.error).map((b) => b.server.id));
    const own = listOwnServers();
    const tried = own.filter((s) => !down.has(s.id));
    const results = await Promise.allSettled(tried.map((s) => getArchiveRecentForServer(s)));
    if (mine !== seq) return;
    const next = new Map<string, ArchiveEntry[]>();
    const bad: string[] = [];
    // Servidor fora do ar entra na linha de falha e mantém a última lista boa.
    for (const s of own) {
      if (!down.has(s.id)) continue;
      bad.push(s.label);
      const old = closedByServer.get(s.id);
      if (old) next.set(s.id, old);
    }
    results.forEach((r, i) => {
      if (r.status === 'fulfilled') next.set(tried[i].id, r.value);
      else {
        bad.push(tried[i].label);
        // Mantém a última lista boa do servidor que falhou agora.
        const old = closedByServer.get(tried[i].id);
        if (old) next.set(tried[i].id, old);
      }
    });
    closedByServer = next;
    failed = bad;
    loaded = true;
  }

  onMount(() => {
    void load();
    const onVisible = () => { if (document.visibilityState === 'visible') void load(); };
    document.addEventListener('visibilitychange', onVisible);
    return () => document.removeEventListener('visibilitychange', onVisible);
  });

  // Sessão que fechou passa a existir só no arquivo: relê pra ela aparecer como fechada.
  let prevLive = new Set<string>();
  $effect(() => {
    const now = new Set(live.map((s) => `${s.serverId}::${s.name}`));
    const shrank = [...prevLive].some((k) => !now.has(k));
    prevLive = now;
    if (shrank) untrack(() => void load());
  });

  // Servidor que voltou ao ar: relê os recentes dele.
  let prevDown = new Set<string>();
  $effect(() => {
    const now = new Set(sessionsStore.byServer.filter((b) => b.error).map((b) => b.server.id));
    const recovered = [...prevDown].some((id) => !now.has(id));
    prevDown = now;
    if (recovered) untrack(() => void load());
  });

  function open(row: (typeof rows)[number]) {
    if (row.kind === 'live') {
      onNavigateToChat(row.serverId, row.name);
      return;
    }
    rememberEntry(row.serverId, row.entry);
    window.location.hash = `#/archive/${encodeURIComponent(row.serverId)}/${encodeURIComponent(row.entry.project)}/${encodeURIComponent(row.entry.session_id)}`;
  }

  const providerOf = (name: string, serverId: string) =>
    live.find((s) => s.serverId === serverId && s.name === name)?.provider;
</script>

<div class="conv">
  <button type="button" class="new" onclick={() => { window.location.hash = '#/'; }}>
    <span class="plus" aria-hidden="true">+</span>{m.conversas_nova()}
  </button>
  <h2 class="section">{m.conversas_recentes()}</h2>

  {#if !loaded && rows.length === 0}
    <div class="skeleton" aria-label={m.comum_carregando()}>
      {#each Array(6) as _, i (i)}<div class="sk-row"><span class="sk-bar"></span></div>{/each}
    </div>
  {:else if rows.length === 0 && failed.length === 0}
    <p class="empty">{m.conversas_vazio()}</p>
  {:else}
    <ul>
      {#each rows as row (row.kind === 'live' ? `l:${row.serverId}:${row.name}` : `c:${row.serverId}:${row.entry.project}:${row.entry.session_id}`)}
        <li>
          <button type="button" class="row" onclick={() => open(row)}>
            <span class="icon" aria-hidden="true">
              {#if row.kind === 'live'}
                <ProviderGlyph provider={providerOf(row.name, row.serverId)} size={18} />
                <span class="dot {row.state}"></span>
              {:else}
                <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M21 12a8 8 0 0 1-11.6 7.1L4 20l1-4.6A8 8 0 1 1 21 12z"/></svg>
              {/if}
            </span>
            <span class="title">{row.title}</span>
            <time class="when">{relativeTime(row.at)}</time>
          </button>
        </li>
      {/each}
    </ul>
  {/if}

  {#each failed as servidor (servidor)}
    <p class="failed" role="status">{m.conversas_servidor_falhou({ servidor })}</p>
  {/each}
</div>

<style>
  .conv { background: transparent; padding: 4px 0 24px; }
  .new {
    display: flex; align-items: center; gap: 10px; width: 100%; min-height: 48px; padding: 0 16px;
    background: transparent; border: 0; color: var(--text); font: inherit; font-weight: 600; text-align: left;
  }
  .plus { width: 18px; text-align: center; font-size: 20px; line-height: 1; color: var(--accent); }
  .section {
    margin: 8px 0 0; padding: 8px 16px; font-size: 12px; font-weight: 600; letter-spacing: .02em;
    color: var(--text-muted); text-transform: none;
  }
  ul { list-style: none; margin: 0; padding: 0; }
  .row {
    display: flex; align-items: center; gap: 12px; width: 100%; height: 48px; padding: 0 16px;
    background: transparent; border: 0; color: var(--text); font: inherit; text-align: left;
  }
  .row:active { background: var(--surface-inset, rgba(127, 127, 127, .12)); }
  .icon { position: relative; flex: none; width: 20px; display: grid; place-items: center; color: var(--text-muted); }
  .dot { position: absolute; right: -3px; bottom: -3px; width: 8px; height: 8px; border-radius: 50%; background: var(--text-muted); }
  .dot.working { background: var(--accent); }
  .dot.awaiting_input { background: var(--warning); }
  .title { flex: 1; min-width: 0; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
  .when { flex: none; font-size: 12px; color: var(--text-muted); }
  .empty, .failed { margin: 0; padding: 12px 16px; font-size: 13px; color: var(--text-muted); }
  .failed { color: var(--warning); }
  .sk-row { height: 48px; display: flex; align-items: center; padding: 0 16px; }
  .sk-bar { height: 12px; width: 60%; border-radius: 6px; background: var(--surface-inset, rgba(127, 127, 127, .15)); opacity: .6; }
</style>

// mobile/src/features/sessions/ConversationList.tsx
import { useCallback, useEffect, useMemo, useRef, useState, type ReactElement } from 'react';
import { ActivityIndicator, AppState, FlatList, Pressable, RefreshControl, Text, View } from 'react-native';
import { StyleSheet, useUnistyles } from 'react-native-unistyles';
import { useRouter } from 'expo-router';
import {
  getArchiveRecentForServer,
  mergeConversations,
  rememberEntry,
  relativeTime,
  rotuloEstado,
  type ArchiveEntry,
  type ConversationRow,
  type State,
} from '@hangar/core';
import { useServers } from '../../stores/servers';
import { useSessions } from '../../stores/sessions';
import { Icon } from '../../ui/Icon';
import { ProviderGlyph } from '../../ui/ProviderGlyph';
import { superficie } from '../../theme/superficie';
import * as m from '../../paraglide/messages';

const PILL_DO_ESTADO: Record<State, 'working' | 'idle' | 'input' | 'dead'> = {
  working: 'working',
  idle: 'idle',
  awaiting_input: 'input',
  dead: 'dead',
};

const chave = (r: ConversationRow) =>
  r.kind === 'live' ? `l:${r.serverId}:${r.name}` : `c:${r.serverId}:${r.entry.project}:${r.entry.session_id}`;

// Modo "Conversas" da gaveta: vivas e fechadas juntas, por recência. As vivas vêm do store da lista
// (um stream por servidor, que o SessionList já retém); as fechadas, dos recentes de cada servidor.
export function ConversationList({ header, onClose }: { header: ReactElement; onClose: () => void }) {
  const { theme } = useUnistyles();
  const router = useRouter();
  const servers = useServers((s) => s.servers);
  const rows = useSessions((s) => s.rows);
  const byServer = useSessions((s) => s.byServer);
  const [closedByServer, setClosedByServer] = useState(() => new Map<string, ArchiveEntry[]>());
  // Por id: dois servidores podem ter o mesmo rótulo (o rótulo sai do primeiro número do IP).
  const [failed, setFailed] = useState<{ id: string; label: string }[]>([]);
  const [loaded, setLoaded] = useState(false);
  const [refreshing, setRefreshing] = useState(false);
  const closedRef = useRef(closedByServer);
  const seq = useRef(0);

  const live = useMemo(() => {
    const own = new Set(servers.filter((s) => !s.invite).map((s) => s.id));
    return rows.filter((r) => own.has(r.serverId));
  }, [rows, servers]);
  const list = useMemo(() => mergeConversations(live, closedByServer), [live, closedByServer]);

  const load = useCallback(async () => {
    const mine = ++seq.current;
    // Servidor fora do ar não é consultado: cada tentativa custaria o teto de 8 s da lista inteira.
    const down = new Set(useSessions.getState().byServer.filter((b) => b.error).map((b) => b.server.id));
    const own = useServers.getState().servers.filter((s) => !s.invite);
    const tried = own.filter((s) => !down.has(s.id));
    const results = await Promise.allSettled(tried.map((s) => getArchiveRecentForServer(s)));
    if (mine !== seq.current) return;
    const prev = closedRef.current;
    const next = new Map<string, ArchiveEntry[]>();
    const bad: { id: string; label: string }[] = [];
    // Servidor fora do ar ou que falhou agora entra na linha de falha e mantém a última lista boa.
    for (const s of own) {
      if (!down.has(s.id)) continue;
      bad.push({ id: s.id, label: s.label });
      const old = prev.get(s.id);
      if (old) next.set(s.id, old);
    }
    results.forEach((r, i) => {
      if (r.status === 'fulfilled') next.set(tried[i].id, r.value);
      else {
        bad.push({ id: tried[i].id, label: tried[i].label });
        const old = prev.get(tried[i].id);
        if (old) next.set(tried[i].id, old);
      }
    });
    closedRef.current = next;
    setClosedByServer(next);
    setFailed(bad);
    setLoaded(true);
  }, []);

  useEffect(() => {
    void load();
    const sub = AppState.addEventListener('change', (s) => { if (s === 'active') void load(); });
    return () => {
      seq.current++;
      sub.remove();
    };
  }, [load]);

  // Sessão que fechou passa a existir só no arquivo: relê pra ela aparecer como fechada.
  const liveKeys = live.map((s) => `${s.serverId}::${s.name}`).join('\n');
  const prevLive = useRef(new Set<string>());
  useEffect(() => {
    const now = new Set(liveKeys ? liveKeys.split('\n') : []);
    const shrank = [...prevLive.current].some((k) => !now.has(k));
    prevLive.current = now;
    if (shrank) void load();
  }, [liveKeys, load]);

  // Servidor que voltou ao ar: relê os recentes dele.
  const downKeys = byServer.filter((b) => b.error).map((b) => b.server.id).join('\n');
  const prevDown = useRef(new Set<string>());
  useEffect(() => {
    const now = new Set(downKeys ? downKeys.split('\n') : []);
    const recovered = [...prevDown.current].some((id) => !now.has(id));
    prevDown.current = now;
    if (recovered) void load();
  }, [downKeys, load]);

  const onRefresh = useCallback(() => {
    setRefreshing(true);
    void load().finally(() => setRefreshing(false));
  }, [load]);

  const open = useCallback((row: ConversationRow) => {
    onClose();
    if (row.kind === 'live') {
      router.push(`/s/${row.serverId}/${row.name}` as never);
      return;
    }
    rememberEntry(row.serverId, row.entry);
    router.push(`/archive/${row.serverId}/${encodeURIComponent(row.entry.project)}/${encodeURIComponent(row.entry.session_id)}` as never);
  }, [onClose, router]);

  const muted = theme.tokens.text.muted;
  const renderItem = useCallback(({ item }: { item: ConversationRow }) => {
    const provider = item.kind === 'live' ? live.find((s) => s.serverId === item.serverId && s.name === item.name)?.provider : undefined;
    const estado = item.kind === 'live' ? (item.state as State) : null;
    const when = relativeTime(item.at);
    return (
      <Pressable
        onPress={() => open(item)}
        style={({ pressed }) => [styles.row, pressed && { backgroundColor: superficie(theme, 0.6) }]}
        accessibilityRole="button"
        accessibilityLabel={[item.title, estado && PILL_DO_ESTADO[estado] ? rotuloEstado(estado) : '', when].filter(Boolean).join(', ')}
      >
        <View style={styles.lead}>
          {item.kind === 'live' ? (
            <>
              {provider ? <ProviderGlyph provider={provider} size={18} /> : <Icon name="MessageCircle" size={18} color={muted} />}
              {estado && PILL_DO_ESTADO[estado] ? (
                <View style={[styles.dot, { backgroundColor: theme.tokens.pill[PILL_DO_ESTADO[estado]].fg, borderColor: theme.tokens.bg.base }]} />
              ) : null}
            </>
          ) : (
            <Icon name="MessageCircle" size={18} color={muted} />
          )}
        </View>
        <Text style={[styles.title, { color: theme.tokens.text.primary }]} numberOfLines={1}>{item.title}</Text>
        <Text style={[styles.when, { color: muted }]} numberOfLines={1}>{when}</Text>
      </Pressable>
    );
  }, [live, open, theme, muted]);

  return (
    <FlatList
      data={list}
      keyExtractor={chave}
      renderItem={renderItem}
      ListHeaderComponent={
        <>
          {header}
          <Text style={[styles.section, { color: muted }]} accessibilityRole="header">{m.conversas_recentes()}</Text>
        </>
      }
      ListEmptyComponent={
        !loaded ? (
          <View style={styles.empty}>
            <ActivityIndicator />
            <Text style={[styles.emptyTxt, { color: muted }]}>{m.comum_carregando()}</Text>
          </View>
        ) : failed.length === 0 ? (
          <Text style={[styles.emptyTxt, styles.emptyPad, { color: muted }]}>{m.conversas_vazio()}</Text>
        ) : null
      }
      ListFooterComponent={
        failed.length ? (
          <View>
            {failed.map((s) => (
              <Text key={s.id} style={[styles.failed, { color: theme.tokens.status.warning }]} accessibilityRole="alert">
                {m.conversas_servidor_falhou({ servidor: s.label })}
              </Text>
            ))}
          </View>
        ) : null
      }
      contentContainerStyle={styles.content}
      keyboardShouldPersistTaps="handled"
      refreshControl={<RefreshControl refreshing={refreshing} onRefresh={onRefresh} />}
    />
  );
}

const styles = StyleSheet.create((theme) => ({
  content: { flexGrow: 1, paddingBottom: theme.base.space[2] },
  section: { fontSize: theme.base.text.xs, fontWeight: '600', paddingTop: 12, paddingBottom: 4, paddingHorizontal: 12 },
  row: { flexDirection: 'row', alignItems: 'center', gap: 12, minHeight: 48, paddingHorizontal: 12, borderRadius: theme.base.radius.lg },
  lead: { width: 22, alignItems: 'center' },
  dot: { position: 'absolute', right: -3, bottom: -3, width: 8, height: 8, borderRadius: 4, borderWidth: 1 },
  title: { flex: 1, minWidth: 0, fontSize: theme.base.text.base },
  when: { flexShrink: 0, fontSize: theme.base.text.xs, fontVariant: ['tabular-nums'] },
  empty: { alignItems: 'center', gap: 8, paddingTop: theme.base.space[6] },
  emptyTxt: { fontSize: theme.base.text.sm, textAlign: 'center' },
  emptyPad: { padding: theme.base.space[6] },
  failed: { fontSize: theme.base.text.sm, paddingVertical: 8, paddingHorizontal: 12 },
}));
